### PR TITLE
Sub-Release 2: Release/v0.6.0: Include 404 Page + documentation + stability of the application

### PR DESCRIPTION
**Pull request by saudkhan116**
Includes https://github.com/eclipse-tractusx/digital-product-pass/pull/16 (v0.6.0.0) + https://github.com/eclipse-tractusx/digital-product-pass/pull/17 (v0.6.0.1)

# PR part of release v0.6.0, Sub Release v0.6.0.2

# Why we create this PR?

To update the documention, frontend components, and improve the stability of the application by adding a 404 (Not Found) page 
 
# What we want to achieve with this PR?

Improve the stability and performance of the application

# What is new?

## Added

- 404 and Error message in consumer backend handler

## Updated

- Improved responsiveness from the application
- Upgrade battery pass test data for Passport Semantic version `v3.0.1`

## Deleted
- Removed history table from Dashboard page

### CODE REVIEW

**Comment by matbmoser** [comment]
@saudkhan116 add in what is new the following text:

## Added
- 404 and Error message in consumer backend handler

## Deleted
- Removed history table from Dashboard page 

## Upgrade
- Improved responsiveness from the application 
- Upgrade battery pass test data for Passport Semantic version `v3.0.1`

**Comment by matbmoser** [comment]
@saudkhan116  please update the PR header to 
"Sub-Release 2: Release/v0.6.0: Include 404 Page + documentation + stability of the application"

in order to ease the understanding from this subrelease structure

**Comment by SebastianBezold** [comment]
Hi @saudkhan116, I edited the PR description and removed the issue links, since they point to a closed system and therefore do not add any value for the overall community. If the issues you linked contain valuable information, please transfer it in an open fashion. Either as comment on this PR or in your changelog/docs

**Comment by saudkhan116** [comment]
Hi @SebastianBezold, Thank you for your feedback. Next time, we will take care of the linked issues.

**Pull request merged**
