### PR TITLE
chore: fix backend issues with policies and dsp endpoints/prepared v4.0.1

### LINKED ISSUE #390: [DPP v4.0.0] Transfer issue parsing EDR in edc 0.7.3 in migration to /v3 api
### Current Behavior
image
Getting all the time digital twin not found because transfer could not be started:

image

I could change the transfer status from "transfer.process.started" which was giving a "REQUESTED" status in the EDC:
image

And not callback endpoint was called.

Once I have changed to "transfer.process"  I finally got a way forward and received and error:
image

### Problems found:
- Chart in v4.0.0 was incorrectly created, missing correct policy configuration: 

https://github.com/eclipse-tractusx/digital-product-pass/blob/b9122b3f4a32d51a17cd08e690d71f9793c0ecd0/charts/digital-product-pass/values.yaml#L209

Should be "odrl:use"

- Process event shall be changed from `transfer.process.started` to `transfer.process`:

https://github.com/eclipse-tractusx/digital-product-pass/blob/b9122b3f4a32d51a17cd08e690d71f9793c0ecd0/dpp-backend/digitalproductpass/src/main/java/org/eclipse/tractusx/digitalproductpass/core/services/DataTransferService.java#L1428

It should also be added to the chart configuration...

- AssetId needs to be removed from the transfer process request model, its not needed anymore:
https://github.com/eclipse-tractusx/digital-product-pass/blob/b9122b3f4a32d51a17cd08e690d71f9793c0ecd0/dpp-backend/digitalproductpass/src/main/java/org/eclipse/tractusx/digitalproductpass/core/models/negotiation/request/TransferRequest.java#L47-L48
 
- EDR must be adapted: 
https://github.com/eclipse-tractusx/digital-product-pass/blob/v4.0.0/dpp-backend/digitalproductpass/src/main/java/org/eclipse/tractusx/digitalproductpass/core/models/edc/EndpointDataReference.java 

## Impact and actions

- v4.0.1 Hotfix release is required

### PR DESCRIPTION
**Pull request by matbmoser**
# What we want to achieve with this PR?
 
I found a bug in the chart configuration, and now the release needs to be recreated, or at least the chart release
Additionally there were some issues that needed to be resolved regarding the edc 0.7.3 transfer and the irs integration.  
#390 
Some typos were also found in the dpp-verification documentation and needed to be fixed

# What is new?

### Added

- Added unit tests for the dsp endpoint parsing functionality
- Added digital product pass compatibility matrix file to the repo root path

### Updated

- Updated typos and missing explanations in the dpp-verification documentation.
- Fixed typo in `AttributeCertificationRecord` which short name was `amr`, it was a typo and was corrected to `acr`.
- Aligned charts for dpp-verification add-on configuration in the configmap -> [#390](https://github.com/eclipse-tractusx/digital-product-pass/issues/390)
- @Deprecated old function to parse dsp endpoint with bpns.
- Updated default INT urls to the Association INT environement url path.
- Managed integration of latest IRS version chart: 7.4.0 and tested compatibility

### Deleted

- AssetId field removed from `transfer-request` model. Deprecated by the EDC v0.7.3 V3 Management Api ->  [#390](https://github.com/eclipse-tractusx/digital-product-pass/issues/390)

### Issues Fixed

- Fixed issue with dsp endpoint parsing/building from Digital Twin submodelBody field. -> [#390](https://github.com/eclipse-tractusx/digital-product-pass/issues/390)
- Fixed policy chart misconfiguration for the passport and digital twin registry -> [#390](https://github.com/eclipse-tractusx/digital-product-pass/issues/390)

# Related Issues

Closes #390

### CODE REVIEW

**Comment by matbmoser** [comment]
I am just waiting to have the "maven" repository to be working again so we can execute the IP checks.

**Comment by matbmoser** [comment]
I could finally fix the problem!

**Comment by matbmoser** [comment]
image

**Review by saudkhan116 — APPROVED** [review]
LGTM

**Pull request merged**
