### PR TITLE
[10º] - Release/v2.0.0: Prepare a new release version dpp v2.0.0

### PR DESCRIPTION
**Pull request by saudkhan116**
# Why we create this PR?
 
- Create and configure DPP helm chart to deploy as a astandalone application without any frontend component
- Prepared a helm docs readme guide to run the helm chart

# What we want to achieve with this PR?
 
To achieve the open source reference implementation of DPP reusable backend

# What is new?
 
## Added
- A standalone DPP backend helm chart for the reference implementation

## Updated
- [BREAKING CHANGES]: Updated the path from the backend from `/consumer-backend` to just `/dpp-backend` to declare the to standalone application
- [BREAKINK CHANGES]: Updated the packege name from `org.eclipse.tractusx.productpass` tp `org.eclipse.tractusx.digitalproductpass` to comply with the latest naming convention. And mark the initial version of the backend as a standalone application

### CODE REVIEW

**Comment by matbmoser** [comment]
Ip checks have passed and everything is working

**Comment by matbmoser** [comment]
There is a change in the directories from the backend because of this there is a lot of changes. But is just moving and renaming files.

**Comment by matbmoser** [comment]
I reviewed everysingle one of them with @saudkhan116

**Review by matbmoser — APPROVED** [review]

**Comment by saudkhan116** [comment]
This PR is reviewed with @matbmoser and most of the files are moved/renamed. Everything is fine including IP checks.

**Pull request merged**
