### PR TITLE
Feature/explaining-text: Added tooltip component

### PR DESCRIPTION
**Pull request by matbmoser**
# Why we create this PR?
 
We want to integrate the tooltip component in our application and fix a bug at the bar component at the UI.
 
# What we want to achieve with this PR?
 
We want to allow the users to visualize more details in the passport visualization UI
 
# What is new?
 
## Added
- Added the Tooltip Component
- Added the Bar Component Fix

### CODE REVIEW

**Comment by matbmoser** [comment]
There is 33 files changed because the previous features were not merge yet

**Comment by matbmoser** [comment]
PR contained in #23

**Comment by matbmoser** [comment]
There are license headers missing, there are missing the updates in the change log

**Comment by matbmoser** [comment]
Now it should be  ready to go

**Review by SebastianBezold — APPROVED** [review]
LGTM

**Pull request merged**
